$(function()
{
    $("#MoveMe1").draggable();
    $("#MoveMe9").draggable();
    $("#MoveMe2").draggable();
    $("#MoveMe3").draggable();
    $("#MoveMe4").draggable();
    $("#MoveMe5").draggable();
    $("#MoveMe6").draggable();
    $("#MoveMe7").draggable();
    $("#MoveMe8").draggable();   
    $("#MoveMe0").draggable(); 
    $("#MoveMe10").draggable(); 
    $("#MoveMe11").draggable(); 
    $("#MoveMe12").draggable(); 
    $("#MoveMe13").draggable(); 
    $("#MoveMe14").draggable();                      
   
});